"""UNIT — UC3's generate/validate loop: ActivityGraph and its two agents.

One test per activation bar on the UC3 sequence diagram, everything below each bar mocked:

    AB3.3  ActivityGraph.run          UT-3.3 - UT-3.5   (+ the self-refusal short-circuit)
    AB3.4  GenerativeAgent.generate   UT-3.6, UT-3.7
    AB3.5  ValidativeAgent.validate   UT-3.8, UT-3.9
    (below) parse_verdict — the fail-closed rule both of the above depend on

The LLM is the only collaborator any of these have, so it is the only thing faked. The graph is
constructed with an injected client (`ActivityGraph(llm=...)`) rather than a patched singleton:
the retry policy is arithmetic over verdicts and deserves to be testable without touching global
state.

WHY THE LOOP IS TESTED AT ALL, given it used to be skipped: `ValidativeAgent.validate` returned a
hardcoded `{"valid": True}`, so no draft could ever be rejected, nothing could reach FLAGGED, and
`retry_count` did not exist. These tests are what stop it silently reverting to that — a stub that
always passes is indistinguishable from a working reviewer unless something asserts a rejection.
"""
import pytest

from app.agents.activity_graph import ActivityGraph
from app.agents.agents import GenerationFailedError, GenerativeAgent, ValidativeAgent
from app.prompts.activity_prompts import VALIDATION_SYSTEM_PROMPT, parse_verdict

pytestmark = pytest.mark.unit

DRAFT = "Rhyme Time\n\n1. Clap the onset.\n2. Blend the rime."
PASS = '{"valid": true}'
FAIL = '{"valid": false, "notes": "step 2 cites a rime that is in none of the grounding pages"}'


class _FakeLLM:
    """A client that answers the writer and the reviewer differently, dispatching on `system`.

    `verdicts` is consumed in order and the last entry repeats, so a case says "reject once, then
    accept" without having to know how many times the loop will ask. `drafts` does the same for
    the writer, which is how a test proves the SECOND attempt was reprompted rather than replayed.
    """

    def __init__(self, drafts=None, verdicts=None):
        self.drafts = list(drafts or [DRAFT])
        self.verdicts = list(verdicts or [PASS])
        self.draft_calls: list[str] = []
        self.review_calls: list[str] = []

    def complete(self, prompt, system=None, temperature=None, seed=None):
        if system == VALIDATION_SYSTEM_PROMPT:
            self.review_calls.append(prompt)
            return self.verdicts[min(len(self.review_calls) - 1, len(self.verdicts) - 1)]
        self.draft_calls.append(prompt)
        return self.drafts[min(len(self.draft_calls) - 1, len(self.drafts) - 1)]


def _graph(llm, max_retries=2):
    return ActivityGraph(max_retries=max_retries, llm=llm)


# --------------------------------------------------------------------------- #
# AB3.3 — ActivityGraph.run
# --------------------------------------------------------------------------- #
def test_ut_3_3_validates_on_the_first_attempt():
    """UT-3.3: the reviewer passes the first draft. VALIDATED, retry_count stays 0, and the writer
    is asked exactly once — a loop that regenerates a perfectly good activity is burning money."""
    llm = _FakeLLM(verdicts=[PASS])

    out = _graph(llm).run("write me an activity")

    assert out["status"] == "VALIDATED"
    assert out["retry_count"] == 0
    assert len(llm.draft_calls) == 1
    assert len(llm.review_calls) == 1
    assert out["content"] == DRAFT


def test_ut_3_4_validates_after_one_rejection():
    """UT-3.4: rejected once, then accepted — VALIDATED with retry_count 1 (alt flow 6a)."""
    llm = _FakeLLM(drafts=["first draft", "second draft"], verdicts=[FAIL, PASS])

    out = _graph(llm).run("write me an activity")

    assert out["status"] == "VALIDATED"
    assert out["retry_count"] == 1
    assert len(llm.draft_calls) == 2
    assert out["content"] == "second draft"     # the accepted draft, not the rejected one


def test_ut_3_4b_the_rejection_notes_are_fed_back_into_the_reprompt():
    """UT-3.4 (the load-bearing half): the second prompt CONTAINS the reviewer's notes.

    This is the whole difference between a retry loop and a coin flip. The previous implementation
    re-sent a byte-identical prompt, so a rejected draft was regenerated by a model that had never
    been told what was wrong — and with temperature 0 it would produce the same text again.
    """
    llm = _FakeLLM(drafts=["first draft", "second draft"], verdicts=[FAIL, PASS])

    _graph(llm).run("write me an activity")

    first, second = llm.draft_calls
    assert "step 2 cites a rime" in second       # the reviewer's actual words reached the writer
    assert "step 2 cites a rime" not in first    # and were not there on the first attempt
    assert second.startswith(first)              # the original request is kept, not replaced


def test_ut_3_5_exhausts_retries_and_flags():
    """UT-3.5: the reviewer never accepts. FLAGGED at retry_count == max_retries, with the last
    draft preserved as best_attempt so alt flow 6b has something to surface to the therapist."""
    llm = _FakeLLM(drafts=["a", "b", "c"], verdicts=[FAIL])

    out = _graph(llm, max_retries=2).run("write me an activity")

    assert out["status"] == "FLAGGED"
    assert out["retry_count"] == 2
    assert len(llm.draft_calls) == 3            # the first attempt plus two retries
    assert out["best_attempt"] == "c"
    assert "step 2 cites a rime" in out["notes"]  # why it was flagged reaches the caller


def test_ut_3_5b_max_retries_zero_flags_without_regenerating():
    """UT-3.5 (boundary): with no retries allowed a rejection flags immediately. Guards the
    off-by-one — `retry_count >= max_retries` must stop at 0, not run one attempt anyway."""
    llm = _FakeLLM(verdicts=[FAIL])

    out = _graph(llm, max_retries=0).run("write me an activity")

    assert out["status"] == "FLAGGED"
    assert out["retry_count"] == 0
    assert len(llm.draft_calls) == 1


def test_a_self_refusal_short_circuits_before_the_reviewer():
    """The model emitting INSUFFICIENT_CONTEXT is not a bad activity — it is the model correctly
    declining. Reviewing it would spend every retry rejecting something nobody asked to be
    written, so the graph leaves immediately and the SERVICE turns this into a refusal."""
    llm = _FakeLLM(drafts=["INSUFFICIENT_CONTEXT\n- no phonics pages for this band"])

    out = _graph(llm).run("write me an activity")

    assert out["refused"] is True
    assert out["status"] == "GENERATED"          # never VALIDATED, never FLAGGED
    assert llm.review_calls == []                # the reviewer was never asked
    assert len(llm.draft_calls) == 1             # and no retry was spent


def test_an_unreachable_reviewer_flags_rather_than_passes():
    """A reviewer that raises must not yield a validated activity. Fails closed: the graph treats
    it as a rejection, so a persistently dead reviewer ends FLAGGED for a human rather than
    silently approving unreviewed curriculum content."""
    class _DeadReviewer(_FakeLLM):
        def complete(self, prompt, system=None, temperature=None, seed=None):
            if system == VALIDATION_SYSTEM_PROMPT:
                raise RuntimeError("reviewer timed out")
            return super().complete(prompt, system=system)

    out = _graph(_DeadReviewer()).run("write me an activity")

    assert out["status"] == "FLAGGED"
    assert "could not be reached" in out["notes"]


def test_a_dead_writer_raises_rather_than_flagging():
    """A dead LLM edge is infrastructure, not a bad activity. It must propagate, not be recorded
    as a flagged draft — otherwise an outage looks like a curriculum problem in the database."""
    class _DeadWriter(_FakeLLM):
        def complete(self, prompt, system=None, temperature=None, seed=None):
            raise RuntimeError("connection refused")

    with pytest.raises(GenerationFailedError):
        _graph(_DeadWriter()).run("write me an activity")


# --------------------------------------------------------------------------- #
# AB3.4 — GenerativeAgent.generate
# --------------------------------------------------------------------------- #
def test_ut_3_6_generative_agent_returns_the_draft():
    """UT-3.6: the writer wraps the completion as a GENERATED draft and passes the system prompt
    through — the grounding rules live in that system message, so dropping it un-grounds the model."""
    llm = _FakeLLM()
    agent = GenerativeAgent(llm)

    out = agent.generate("make a rhyming activity", system="SYS")

    assert out == {"content": DRAFT, "status": "GENERATED"}
    assert llm.draft_calls == ["make a rhyming activity"]


@pytest.mark.parametrize("completion", ["", "   ", None])
def test_ut_3_7_an_empty_completion_is_a_failure_not_a_draft(completion):
    """UT-3.7: an empty completion raises rather than returning. Flowing on as `content` it would
    be reviewed and rejected as if the model had written a bad activity, sending a therapist after
    a prompt problem when the LLM edge is what is broken."""
    class _Empty(_FakeLLM):
        def complete(self, prompt, system=None, temperature=None, seed=None):
            return completion

    with pytest.raises(GenerationFailedError):
        GenerativeAgent(_Empty()).generate("prompt")


def test_ut_3_7b_a_transport_failure_is_wrapped():
    """UT-3.7: a raising client surfaces as GenerationFailedError, so callers catch one type
    rather than every exception httpx and the SDKs can throw."""
    class _Boom(_FakeLLM):
        def complete(self, prompt, system=None, temperature=None, seed=None):
            raise TimeoutError("read timeout")

    with pytest.raises(GenerationFailedError):
        GenerativeAgent(_Boom()).generate("prompt")


# --------------------------------------------------------------------------- #
# AB3.5 — ValidativeAgent.validate
# --------------------------------------------------------------------------- #
def test_ut_3_8_passes_a_compliant_activity():
    """UT-3.8: a passing verdict comes back as valid with no notes."""
    llm = _FakeLLM(verdicts=[PASS])

    out = ValidativeAgent(llm).validate({"content": DRAFT}, [], {})

    assert out == {"valid": True, "notes": ""}


def test_ut_3_9_fails_with_actionable_feedback():
    """UT-3.9: a failing verdict carries the notes, because they are the next prompt's payload."""
    llm = _FakeLLM(verdicts=[FAIL])

    out = ValidativeAgent(llm).validate({"content": DRAFT}, [], {})

    assert out["valid"] is False
    assert "step 2 cites a rime" in out["notes"]


def test_the_reviewer_is_shown_the_grounding_it_must_judge_against():
    """Criterion 1 of the framework is "nothing outside the grounding", which is unanswerable
    without the grounding. A reviewer shown only the draft can check that it reads well and
    nothing else — which is the failure the hardcoded `valid: True` stub already was."""
    llm = _FakeLLM(verdicts=[PASS])
    chunk = {"activity_title": "Onset and rime", "content_md": "Clap the onset.",
             "concept": "onset_rime", "stage": "practice",
             "source_file": "2) A1.pdf", "page_start": "14"}

    ValidativeAgent(llm).validate({"content": DRAFT}, [chunk], {"band": "A"})

    sent = llm.review_calls[0]
    assert "Onset and rime" in sent          # the chunk title
    assert "Clap the onset." in sent         # and its actual body, not just a label
    assert DRAFT in sent                     # alongside the draft under review


def test_an_empty_draft_is_rejected_without_calling_the_model():
    """Nothing to review is not a pass, and is not worth an LLM call either."""
    llm = _FakeLLM()

    out = ValidativeAgent(llm).validate({"content": "   "}, [], {})

    assert out["valid"] is False
    assert llm.review_calls == []


# --------------------------------------------------------------------------- #
# parse_verdict — the fail-closed rule
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("raw", [
    '{"valid": true}',
    '```json\n{"valid": true}\n```',                       # fenced, as models habitually do
    'Here is my verdict:\n{"valid": true}\nHope that helps.',  # padded with prose
])
def test_a_pass_is_read_through_the_wrappers_models_add(raw):
    assert parse_verdict(raw)["valid"] is True


@pytest.mark.parametrize("raw", [
    None, "", "   ",
    "Looks good to me!",                    # prose approval with no JSON at all
    '{"valid": "yes"}',                     # right shape, wrong type
    '{"verdict": true}',                    # wrong key
    '{"valid": true',                       # truncated
])
def test_an_unreadable_verdict_fails_closed(raw):
    """A review that did not happen is not an approval. This is the exact bug the old
    `return {"valid": True}` stub was, so it is asserted rather than assumed."""
    out = parse_verdict(raw)

    assert out["valid"] is False
    assert out["notes"]                     # and it says why, so the retry is informed
