"""UNIT — the cohort ingest CLI's row builder (Subsystem 2, UC2).

    AB2.16  scripts.ingest_dial_data.build_rows()  UT-2.43, UT-2.44

Extends the PM3 UC2 test plan (see test_profiling_algorithm_cluster.py for why).

WHAT THESE PROTECT. Since the 2026-08-07 merge the anonymised research cohort shares the
`learners` table with the therapist's caseload, and a learner can be in both. The upsert
updates the columns its payload carries and leaves the rest, so `STORED` — the exact list of
columns `build_rows` emits — is the whole safety mechanism: it must carry every workbook-derived
column and NONE of `pseudonym`, `tier` or `on_caseload`. Get that wrong and a routine re-ingest
anonymises real learners with no error anywhere.
"""
import pytest

pd = pytest.importorskip(
    "pandas",
    reason="pandas is in requirements-analysis.txt (notebook + ingest only), not the API's "
           "runtime deps — the workbook is never read by the running service.",
)

from app.ingestion.dial_workbook import (  # noqa: E402  (must follow the importorskip)
    _band_group,
    _collapse_writing,
    percentiles,
)
from scripts.ingest_dial_data import (  # noqa: E402
    STORED, build_rows, build_sitting_rows,
)

pytestmark = pytest.mark.unit

LEARNER_UUID = "11111111-1111-1111-1111-111111111111"


def frame(rows):
    """A cohort frame with every column build_rows() reads, defaults filled in."""
    base = {
        "student_id": "Student 0001", "semester": "2026 Sem 1", "band": "A2",
        "school_level": "Primary", "age": 9, "phonics": 20.0,
        "word_reading_accuracy": 8.0, "word_spelling": 5.0,
        "narrative_writing": 0.0, "exposition_writing": 0.0, "persuasive_writing": 0.0,
        "fluency_mark": 16.0,
    }
    df = pd.DataFrame([{**base, **r} for r in rows])
    df["writing"], df["writing_genre"] = _collapse_writing(df)
    df["band_group"] = _band_group(df["band"])
    return df.join(percentiles(df))


# ── what the ingest is allowed to write ───────────────────────────────────────
def test_the_payload_never_carries_caseload_identity():
    """UT-2.43: THE ONE THAT PROTECTS REAL LEARNERS.

    A learner can be on the caseload AND in the workbook. The upsert updates only the columns
    the payload carries, so omitting these three is what lets a re-ingest refresh someone's
    marks without erasing their name. There is no read-back to fall back on — absence IS the
    mechanism, which is why it is asserted directly rather than inferred from behaviour.
    """
    rows = build_rows(frame([{"student_id": "Student 0142"}]), {}, {})

    for protected in ("pseudonym", "tier", "on_caseload"):
        assert protected not in rows[0], f"{protected} in the payload would overwrite a real learner"
        assert protected not in STORED


def test_the_payload_carries_the_workbook_key():
    """UT-2.43: student_id is what the upsert conflicts on, so every row must have one."""
    rows = build_rows(frame([{"student_id": "Student 0142"}]), {}, {})

    assert rows[0]["student_id"] == "Student 0142"


def test_no_row_carries_the_primary_key():
    """UT-2.43: `id` is generated by Postgres and stable across re-ingests.

    Sending one would either collide with an existing learner or replace their uuid, orphaning
    every learner_sittings and assessment_records row that pointed at it.
    """
    rows = build_rows(frame([{"student_id": "Student 0142"}]), {}, {})

    assert "id" not in rows[0]


# ── percentiles ride along ────────────────────────────────────────────────────
def test_percentile_columns_are_stored():
    """UT-2.44: the radar chart's percentiles are written, not just computed."""
    rows = build_rows(frame([
        {"student_id": "S1", "phonics": 10.0},
        {"student_id": "S2", "phonics": 30.0},
    ]), {}, {})

    assert rows[1]["phonics_pct"] == 100.0
    assert rows[0]["phonics_pct"] == 50.0


def test_a_missing_percentile_is_none_not_nan():
    """UT-2.44: NaN is not JSON.

    NaN is a float, so it survives json.dumps as the bare literal `NaN` — which PostgREST
    rejects with a parse error that names no column. Band A learners have no writing mark and
    therefore no writing percentile, so this is every band A row, not a rare case.
    """
    rows = build_rows(frame([{"student_id": "S1"}]), {}, {})   # all genres 0 -> no writing

    assert rows[0]["writing_pct"] is None
    assert rows[0]["writing"] is None


# ── cluster labels ────────────────────────────────────────────────────────────
def test_both_cluster_scopes_are_written_independently():
    """UT-2.43: a student can have a cohort label and no band label.

    The two models label different populations — every scored learner gets a cohort label, but
    a learner whose band group is too small to fit gets no band label.
    """
    rows = build_rows(frame([{"student_id": "S1"}]), {}, {"S1": "Cohort 2"})

    assert rows[0]["cluster_cohort"] == "Cohort 2"
    assert rows[0]["cluster_band"] is None


# ── the sitting history ───────────────────────────────────────────────────────
# `build_sitting_rows` turns the WHOLE workbook into learner_sittings rows — the ~17,000 the
# ingest used to discard, which are what the profile page's progress chart plots.
def test_sittings_are_keyed_by_the_learners_uuid():
    """UT-2.46: the workbook knows student ids; `learner_sittings` needs the uuid.

    The FK is to learners(id), so the mapping is resolved by reading the learners back after
    they are upserted — a student new to the table has no uuid until then.
    """
    rows = build_sitting_rows(
        frame([{"student_id": "Student 0142", "semester": "2026 Sem 1"}]),
        {"Student 0142": LEARNER_UUID},
    )

    assert rows[0]["learner_id"] == LEARNER_UUID
    assert "student_id" not in rows[0], "the workbook key does not belong on a sitting"


def test_a_sitting_with_no_learner_is_dropped_not_written_null():
    """UT-2.46: one unresolvable student must not cost the other 22,891 rows.

    Postgres would reject the whole batch on a null FK, and PostgREST's error names no row —
    so the ingest drops it and reports the count instead.
    """
    rows = build_sitting_rows(
        frame([
            {"student_id": "Student 0142", "semester": "2026 Sem 1"},
            {"student_id": "Student 9999", "semester": "2026 Sem 1"},
        ]),
        {"Student 0142": LEARNER_UUID},
    )

    assert len(rows) == 1
    assert all(r["learner_id"] for r in rows)


def test_every_sitting_is_marked_as_coming_from_the_workbook():
    """UT-2.46: `source` tells an ingested sitting from one UC1 uploaded.

    Both writers share the table, and only the provenance distinguishes them once the marks
    are stored.
    """
    rows = build_sitting_rows(
        frame([{"student_id": "Student 0142", "semester": "2026 Sem 1"}]),
        {"Student 0142": LEARNER_UUID},
    )

    assert rows[0]["source"] == "workbook"


def test_a_sittings_nan_becomes_none():
    """UT-2.47: NaN is not JSON, on this table as much as on `learners`."""
    rows = build_sitting_rows(
        frame([{"student_id": "Student 0142", "semester": "2026 Sem 1"}]),   # no writing genre
        {"Student 0142": LEARNER_UUID},
    )

    assert rows[0]["writing"] is None
    assert rows[0]["writing_pct"] is None


def test_percentiles_can_rank_within_a_semester():
    """UT-2.47: a sitting is ranked against the SAME PAPER in the SAME SEMESTER.

    THE POINT OF THE `by` PARAMETER. Ranking a 2022 mark against the 2026 population would make
    the progress line move as the cohort around the learner changes rather than as the learner
    does. Here the same mark is top of its semester in one year and bottom in the next, and
    only a semester-scoped rank can say so.
    """
    df = frame([
        {"student_id": "S1", "semester": "2022 Sem 1", "band": "A2", "phonics": 20.0},
        {"student_id": "S2", "semester": "2022 Sem 1", "band": "A2", "phonics": 10.0},
        {"student_id": "S1", "semester": "2026 Sem 1", "band": "A2", "phonics": 20.0},
        {"student_id": "S2", "semester": "2026 Sem 1", "band": "A2", "phonics": 30.0},
    ])
    out = percentiles(df, by=("semester", "band_group"))["phonics_pct"]

    assert list(out) == [100.0, 50.0, 50.0, 100.0]
